"""education

Revision ID: 0654b11a0295
Revises: 31b6445da306
Create Date: 2025-05-30 16:56:17.353287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0654b11a0295'
down_revision = '31b6445da306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=512), nullable=False),
    sa.Column('course_name', sa.String(length=512), nullable=False),
    sa.Column('start_year', sa.String(length=10), nullable=True),
    sa.Column('end_year', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('education')
    # ### end Alembic commands ###
