"""one_liner and resume

Revision ID: 31b6445da306
Revises: f693205362bf
Create Date: 2025-05-30 14:46:10.964668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b6445da306'
down_revision = 'f693205362bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endorsement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endorsed_by', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endorsed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endorsed_by', 'skill_id', name='unique_endorsement')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_liner', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resume', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_column('endorsement_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endorsement_count', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('resume')
        batch_op.drop_column('one_liner')

    op.drop_table('endorsement')
    # ### end Alembic commands ###
