"""college

Revision ID: 5632e10db5de
Revises: 1ce461eb9324
Create Date: 2025-06-13 23:08:51.454332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5632e10db5de'
down_revision = '1ce461eb9324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('start_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('college')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('start_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
